version: '3'
services:
  web:
    build: .
    ports:
      - "9930:5000"
    environment:
      - MANGA_COLLECTION_DIRECTORY=/downloads
    volumes:
      - /mnt/local-usb/MangaCollection:/downloads
    depends_on:
      - nginx